"""Add role and is_approved fields to users

Revision ID: a4bd6b148f59
Revises: 
Create Date: 2025-12-02 14:51:20.308671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4bd6b148f59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with default values for existing rows
    op.add_column('users', sa.Column('role', sa.String(), nullable=False, server_default='user'))
    op.add_column('users', sa.Column('is_approved', sa.Boolean(), nullable=False, server_default='0'))

    # Update existing users to be approved and have role 'admin' if they're the first user
    # This allows the first registered user to become admin
    conn = op.get_bind()
    conn.execute(sa.text("UPDATE users SET is_approved = 1 WHERE id IN (SELECT id FROM users ORDER BY created_at LIMIT 1)"))
    conn.execute(sa.text("UPDATE users SET role = 'admin' WHERE id IN (SELECT id FROM users ORDER BY created_at LIMIT 1)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_approved')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
