"""Add username and email verification fields

Revision ID: b6bf573d4cb1
Revises: a4bd6b148f59
Create Date: 2025-12-02 15:03:21.566573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6bf573d4cb1'
down_revision: Union[str, Sequence[str], None] = 'a4bd6b148f59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    # Check if username column already exists
    result = conn.execute(sa.text("PRAGMA table_info(users)"))
    columns = [row[1] for row in result]

    if 'username' not in columns:
        # Add username column as nullable temporarily
        op.add_column('users', sa.Column('username', sa.String(), nullable=True))

        # Generate unique usernames from email for existing users
        users = conn.execute(sa.text("SELECT id, email FROM users")).fetchall()

        # Generate unique usernames
        username_map = {}
        for user_id, email in users:
            base_username = email.split('@')[0].lower()
            username = base_username
            counter = 1

            # If username already exists, append number
            while username in username_map.values():
                username = f"{base_username}{counter}"
                counter += 1

            username_map[user_id] = username

        # Update each user with their unique username
        for user_id, username in username_map.items():
            conn.execute(
                sa.text("UPDATE users SET username = :username WHERE id = :id"),
                {"username": username, "id": user_id}
            )

        # Create unique index for username
        op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    else:
        # Username already exists, just fill in missing values
        users = conn.execute(sa.text("SELECT id, email FROM users WHERE username IS NULL")).fetchall()

        if users:
            # Get existing usernames to avoid duplicates
            existing = conn.execute(sa.text("SELECT username FROM users WHERE username IS NOT NULL")).fetchall()
            existing_usernames = set(row[0] for row in existing)

            for user_id, email in users:
                base_username = email.split('@')[0].lower()
                username = base_username
                counter = 1

                while username in existing_usernames:
                    username = f"{base_username}{counter}"
                    counter += 1

                existing_usernames.add(username)
                conn.execute(
                    sa.text("UPDATE users SET username = :username WHERE id = :id"),
                    {"username": username, "id": user_id}
                )

    # Add email verification columns
    if 'email_verification_token' not in columns:
        op.add_column('users', sa.Column('email_verification_token', sa.String(), nullable=True))
    if 'email_verification_sent_at' not in columns:
        op.add_column('users', sa.Column('email_verification_sent_at', sa.DateTime(), nullable=True))

    # Mark existing users as verified (legacy users)
    conn.execute(sa.text("UPDATE users SET is_verified = 1 WHERE is_verified = 0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'email_verification_sent_at')
    op.drop_column('users', 'email_verification_token')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
